name: wamp_client
description: A library for WAMP protocol client.  WAMP is the Web Application Messaging Protocol (https://wamp-proto.org)
version: 0.1.2
homepage: https://github.com/kkazuo/dart-wamp-client
author: Koga Kazuo <obiwanko@me.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

#dependencies:
#  web_socket_channel: ^1.0.9

dev_dependencies:
  test: ^0.12.0
