name: wamp_client
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/kkazuo/dart-wamp-client
author: Koga Kazuo <obiwanko@me.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
